web/myadmin/urls.py
from django.conf.urls import url
from . views import IndexViews,UsersViews,CatesViews,GoodsViews

from .views import OrderViews

urlpatterns = [
    # 支付流程
    # url(r'^auth/group/edit/$', OrderViews.myhome_pay_result, name="myhome_pay_result"),

	# 登录
    url(r'^login/$',IndexViews.myadmin_login,name="myadmin_login"),
    # 登录处理 - 首页
    url(r'^dologin/$',IndexViews.myadmin_dologin,name="myadmin_dologin"),
    # 验证码
    url(r'^varifycode/$',IndexViews.varifycode,name="myadmin_vcode"),
    # 退出登录
    url(r'^uplogin/$',IndexViews.myadmin_uplogin,name="myadmin_uplogin"),


    # 首页
    url(r'^index/$',IndexViews.index,name="index"),


    # 会员管理
    url(r'^user/add/$',UsersViews.user_add,name="myadmin_user_add"),
    url(r'^user/insert/$',UsersViews.user_insert,name="myadmin_user_insert"),
    url(r'^user/index/$',UsersViews.user_index,name="myadmin_user_index"),
    # 会员用户的编辑
    url(r'^user/edit/$',UsersViews.user_edit,name="myadmin_user_edit"),
    # url(r'^user/update/$',UsersViews.user_edit,name='myadmin_user_update'),
    # 会员状态修改
    url(r'^user/setstatus/$',UsersViews.user_set_status,name='myadmin_user_set_status'),


    # 商品分类管理
    # 商品分类数据 添加
    url(r'^cate/add/$',CatesViews.cate_add,name="myadmin_cate_add"),
    # 商品分类列表
    url(r'^cate/index/$',CatesViews.cate_index,name="myadmin_cate_index"),
    # 商品分类删除
    url(r'^cate/del/$',CatesViews.cate_del,name="myadmin_cate_del"),
    # ----编辑
    url(r'^cate/edit/$',CatesViews.cate_edit,name="myadmin_cate_edit"),


    # 商品管理
    url(r'^good/add/$',GoodsViews.good_add,name="myadmin_good_add"),
    url(r'^good/insert/$',GoodsViews.good_insert,name="myadmin_good_insert"),

    url(r'^good/index/$',GoodsViews.good_index,name="myadmin_good_index"),
    # 删除goods_del
    url(r'^good/del/$',GoodsViews.good_del,name="myadmin_good_del"),
    # 编辑 -- 状态
    url(r'^good/status/$',GoodsViews.good_status,name="myadmin_good_status"),
    # 商品编辑
    url(r'^good/edit/$',GoodsViews.good_edit,name="myadmin_good_edit"),


    # 权限管理
    # 管理员管理
    url(r'^auth/user/idnex/$',IndexViews.myadmin_authuser_index,name="myadmin_authuser_index"), # 列表
    url(r'^auth/user/add/$',IndexViews.myadmin_authuser_add,name="myadmin_authuser_add"), # 添加
    url(r'^auth/user/insert/$',IndexViews.myadmin_authuser_insert,name="myadmin_authuser_insert"), # 执行添加
    url(r'^auth/user/del/$', IndexViews.myadmin_authuser_del, name="myadmin_authuser_del"),  # 删除
    url(r'^auth/user/edit/$', IndexViews.myadmin_authuser_edit, name="myadmin_authuser_edit"),  # 编辑

    # 权限组管理
    url(r'^auth/group/idnex/$',IndexViews.myadmin_authgroup_index,name="myadmin_authgroup_index"),
    url(r'^auth/group/add/$',IndexViews.myadmin_authgroup_add,name="myadmin_authgroup_add"),
    url(r'^auth/group/insert/$',IndexViews.myadmin_authgroup_insert,name="myadmin_authgroup_insert"),
    url(r'^auth/group/del/$', IndexViews.myadmin_authgroup_del, name="myadmin_authgroup_del"),
    url(r'^auth/group/edit/$', IndexViews.myadmin_authgroup_edit, name="myadmin_authgroup_edit"),



]

web/web/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^ueditor/', include('ueditor.urls')),
    # url(r'^admin/', admin.site.urls),
    url(r'^myadmin/', include('myadmin.urls')),
    url(r'^',include('myhome.urls')),
]

web/myadmin/models.py
from django.db import models

# Create your models here.


# 定义会员模型
class Users(models.Model):
    nikename = models.CharField(max_length=20,null=True)
    password = models.CharField(max_length=77)
    # phone = models.CharField(max_length=11,unique=True)
    phone = models.CharField(max_length=11)
    email = models.CharField(max_length=100)
    age = models.IntegerField(null=True)
    pic_url = models.CharField(max_length=100)
    SEX_CHOICES = (
        (0, '女'),
        (1, '男'),
    )
    sex = models.CharField(max_length=1,null=True,choices=SEX_CHOICES)
    # 0 正常  1禁用  2 删除 ....
    status = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True)

    # 自定义会员管理权限
    class Meta:
        permissions = (
            ('show_Users','查看会员列表权限'),
            ('create_Users','添加会员权限'),
            ('edit_Users','修改会员信息权限'),
            ('remove_Users','删除会员权限'),
        )


# 商品分类  -- 无限分类(一般2~3级)
class Cates(models.Model):
    name = models.CharField(max_length=32)
    pid = models.IntegerField() # 父类id
    path = models.CharField(max_length=50)
    # 自定义商品分类管理权限
    class Meta:
        permissions = (
            ('show_Cates','查看商品分类列表权限'),
            ('create_Cates','添加商品分类权限'),
            ('edit_Cates','修改商品分类信息权限'),
            ('remove_Cates','删除商品分类权限'),
        )

# 商品模型
class Goods(models.Model):
    # 所属分类id 、商品name、商品标题、价格、数量、图片-路径、商品的描述、销量、点击次数
    cateid = models.ForeignKey(to='Cates', to_field='id') # 多对一
    goodsname = models.CharField(max_length=50)
    title = models.CharField(max_length=255)
    price = models.FloatField()
    goodsnum = models.IntegerField()
    pic_url = models.CharField(max_length=255)
    goodsinfo = models.TextField()
    ordernum = models.IntegerField(default=0)
    clicknum = models.IntegerField(default=0)
    # 状态--0新品、1热卖、2推荐、3下架   、 添加时间
    status = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True)
    # 自定义会员管理权限
    class Meta:
        permissions = (
            ('show_Goods','查看商品列表权限'),
            ('create_Goods','添加商品权限'),
            ('edit_Goods','修改商品信息权限'),
            ('remove_Goods','删除商品权限'),
        )



# 购物车模型
class Cart(models.Model):
    # id 用户id 商品id 数量
    uid = models.ForeignKey(to="Users", to_field="id") # 多对一 绑定会员id
    goodsid = models.ForeignKey(to="Goods", to_field="id")
    num = models.IntegerField()


# 订单模型
class Order(models.Model):
    # 多对一 绑定会员id
    uid = models.ForeignKey(to="Users", to_field="id")
    username = models.CharField(max_length=20) #会员名
    phone = models.CharField(max_length=15)
    address = models.CharField(max_length=255) #地址
    totalprice = models.FloatField() #总价
    # 0未支付、1已支付、2已发货、3已收货、4已评论
    status = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True) # 添加时间
    paytime = models.DateTimeField(null=True) # 付款时间

    paytype = models.IntegerField(default=0) # 支付类型
    # 自定义会员管理权限
    class Meta:
        permissions = (
            ('show_Order','查看订单列表权限'),
            # 订单没有添加
            ('create_Order','添加订单权限'),
            ('edit_Order','修改订单信息权限'),
            ('remove_Order','删除订单权限'),
        )


#　订单详情
class OrderInfo(models.Model):
    # 多对一 绑定订单id
    orderid = models.ForeignKey(to="Order", to_field="id")
    # 多对一 绑定商品id
    goodsid = models.ForeignKey(to='Goods', to_field="id")
    num = models.IntegerField()

web/myadmin/views/AdminMiddleware.py
from django.shortcuts import render
from django.http import HttpResponse
import re

from django.core.urlresolvers import reverse

class AdminLoginMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response
        # One-time configuration and initialization.

    def __call__(self, request):
        '''
        # 检测当前的请求是否已经登录,如果已经登录,.则放行,如果未登录,则跳转到登录页
        # 获取当前用户的请求路径  /admin/开头  但不是 /admin/login/  /admin/dologin/   /admin/verifycode
        urllist = ['/admin/login','/admin/dologin','/admin/vcode']
        # 判断是否进入了后台,并且不是进入登录页面
        if re.match('/admin/',request.path) and request.path not in urllist:

            # 检测session中是否存在 adminlogin的数据记录
            if request.session.get('Vuser','') == '':
                # 如果在session没有记录,则证明没有登录,跳转到登录页面
                return HttpResponse('<script>alert("请先登录");location.href="/admin/login";</script>')
        '''

        # 用户的请求路径
        path =request.path
        # 开通的访问的路由--登录、登录处理、验证码
        arr = ['/myadmin/login/','/myadmin/dologin/','/myadmin/varifycode/']
        # 检测会员是否访问 后台 -- re开头检测
        if(re.match('/myadmin/',path) and path not in arr):
            AdminUser = request.session.get('AdminUser',None)
            # 是否已经登录
            if not AdminUser:
                # 没有登陆则提示
                return HttpResponse('<script>alert("请先登录");location.href="/myadmin/login/";</script>')

        # # 前台登录的验证中间件
        # homeurl = [
        #     reverse()
        # ]
        # # 判断是否访问需要登录的路由
        # if path in homeurl:
        #     # 是否登录
        #     if not request.session.get('VipUser',None):
        #         # 没有登录则
        #         return HttpResponse('<script>alert("请先登录");location.href="/login/";</script>')


        # 放行--该有的相应内容都响应
        response = self.get_response(request)
        return response

web/myadmin/views/CatesViews.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse

# Create your views here.
from .. models import Cates

from django.db.models import Q

from django.contrib.auth.decorators import permission_required

# 商品类别添加
@permission_required('myadmin.create_Cates',raise_exception=True)
def cate_add(request):
    if(request.method == 'POST'):
    	# 接收数据
    	data = {}
    	data['name'] = request.POST.get('name')
    	data['pid'] = request.POST.get('pid')
    	# data['path'] = '0,'

    	if data['pid']== '0':
    		data['path'] = '0,'
    	else:
    		# 获取父级路径
    		pob = Cates.objects.get(id = data['pid'])
    		# 拼接path
    		data['path'] = pob.path + data['pid'] + ','
    	print(data)

    	# 数据添加
    	ob = Cates(**data)
    	ob.save()
    	return HttpResponse('<script>alert("添加成功");location.href="/myadmin/cate/index/";</script>')
    else:
    	# 获取当前已有的 分类数据
    	catelist = Cates.objects.all()
    	catelist = get_cates_all(catelist)
    	# 分配
    	context = {'catelist': catelist} # catelist 为里面的数据
    	# 加载商品模板页面
    	return render(request,'myadmin/cates/add.html',context)

# 商品类别列表
@permission_required('myadmin.show_Cates',raise_exception=True)
def cate_index(request):
	data = Cates.objects.all() 

	# 获取搜索条件
	types = request.GET.get('types',None)
	keywords = request.GET.get('keywords',None)
	# 搜索判断
	if types=="all":
		# 筛选处理－－包含
		data = data.filter(Q(id__contains = keywords) | Q(name__contains = keywords))
		
	# elif types=='id':
	#     data = data.filter(id__contains = keywords)
	elif types:
		search = {types+'__contains': keywords}
		data = data.filter(**search)
	

	# 导入分页类
	from django.core.paginator import Paginator
	p = Paginator(data, 10) # 实例化
    # 获取当前的页码数
	page_index = request.GET.get('page',1)
    # 获取当前 页数
	user_list = p.page(page_index)

	data = get_cates_all(data) #缩减
		
	# res = Cates.objects.all()
	context = {'catelist': data,'userlist': user_list}
	return render(request,'myadmin/cates/index.html',context)

# 排序+缩减格式化
def get_cates_all(data):
	# 排列方式 
	# sql = "SELECT *,CONCAT(path,id) AS paths FROM myadmin_cates ORDER BY paths;"
	# sql注入 -- 容易出现漏洞
	# data = Cates.objects.raw(sql)s

	# django的排序
	data = data.extra(select = {'paths':'concat(path,id)'}).order_by('paths')

	# 缩进处理
	for i in data:
		# lens = len(i.path.split(',')) - 2
		lens = i.path.count(',') - 1
		i.tab = '|——'*lens
		# print(lens)

		if i.pid == 0:
			i.pname = '顶级'
		else:
			pob = Cates.objects.get(id = i.id)
			i.pname = pob.name
		# print(i.tab+i.name)
	return data

# 商品分类删除
@permission_required('myadmin.remove_Cates',raise_exception=True)
def cate_del(request):

	# this window--窗体对象 --> 文档对象(DOM), location(地址对象), history(历史对象)

	# 接收id，获取对象
	cid = request.GET.get('cid')

	# 判断分类下是否有子类
	res = Cates.objects.filter(pid=cid).count()
	if res:
		return JsonResponse({'msg':'该类别下还有分类，不可删除','code':1})

	# 分类下是否有商品--后期完成

	# 执行删除
	ob = Cates.objects.get(id=cid)
	ob.delete()

	return JsonResponse({'msg':'删除成功','code':0})

# ---name编辑
@permission_required('myadmin.edit_Cates',raise_exception=True)
def cate_edit(request):
	try:
		# 接收id
		cid = request.GET.get('cid')
		# 接收修改后的name
		newname = request.GET.get('newname')

		# 入库
		ob = Cates.objects.get(id=cid)
		ob.name = newname
		ob.save()
		data = {'msg': '更新成功', 'code': 0}
	except:
		data = {'msg': '更新失败，请重新操作', 'code': 1}

	return JsonResponse(data)

web/myadmin/views/GoodsViews.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse

from . CatesViews import get_cates_all # 商品分类下拉框函数
from . UsersViews import uploads_pic # 图片处理函数
from .. models import Cates,Goods

from django.db.models import Q

from django.contrib.auth.decorators import permission_required

# Create your views here.
# show
# create
# edit
# remove
# 商品添加 -- 内容填写页面
@permission_required('myadmin.create_Goods',raise_exception=True)
def good_add(request):
    # 下拉框
    data = Cates.objects.all()
    catelist = get_cates_all(data)
    # 分配
    context = {'catelist': catelist} # catelist 为里面的数据  


    return render(request,'myadmin/goods/add.html',context)

# 商品添加-执行
# @permission_required('myadmin.create_Goods',raise_exception=True)
def good_insert(request):
	# 接收表单数据
    data = request.POST.dict()
    data.pop('csrfmiddlewaretoken')
    # print(111,data)
    # return HttpResponse('添加成功')
    data['cateid'] = Cates.objects.get(id = data['cateid'])

    # 头像上传
    # 接收上传的文件
    myfile = request.FILES.get('pic',None)
    if not myfile:
        # 没有选择头像上传,
        return HttpResponse('<script>alert("没有商品图片上次上传");history.back(-1);</script>')

    # 处理头像的上传  1.jpg ==> [1,jpg]
    data['pic_url'] = uploads_pic(myfile)

    # print(data)
    
    try:
        # 创建模型,添加数据
        ob = Goods(**data)
        ob.save()
        return HttpResponse('<script>alert("添加成功");location.href="/myadmin/good/index/";</script>')
    except:
        pass
    return HttpResponse('<script>alert("添加失败");history.back(-1);</script>')

# 商品列表
@permission_required('myadmin.show_Goods',raise_exception=True)
def good_index(request):
    
    # data = Cates.objects.all()
    # data = get_cates_all(data)
    data = Goods.objects.all()

    # 获取搜索条件
    types = request.GET.get('types',None)
    keywords = request.GET.get('keywords',None)
    # 搜索判断
    if types=="all":#price cateid
        # # 父类查询
        # res = Cates.objects.filter(name__contains = keywords)
        # for i in res:
        #     data = data.filter(cateid=i.id)
            
        data = data.filter(Q(id__contains = keywords) | Q(goodsname__contains = keywords))

    # 价格区间
    # elif types=="price":
    #     data = data.filter(id__contains = keywords)
    # 所属分类
    elif types=="cateid":
        # 父类查询
        res = Cates.objects.filter(name__contains = keywords)
        for i in res:
            data = data.filter(cateid=i.id)

        # [data.filter(cateid=i.id) for i in res]
        # data = data.filter(cateid__in=[data.filter(cateid=i.id).pid for i in res])
    elif types:
        search = {types+'__contains': keywords}
        data = data.filter(**search)

    # 导入分页类
    from django.core.paginator import Paginator
    p = Paginator(data, 10) # 实例化
    # 获取当前的页码数
    page_index = request.GET.get('page',1)
    # 获取当前 页数
    user_list = p.page(page_index)

    context = {'goodslist': data,'userlist': user_list}

    return render(request,'myadmin/goods/index.html',context)

@permission_required('myadmin.remove_Goods',raise_exception=True)
# 商品分类删除
def good_del(request):

    # this window--窗体对象 --> 文档对象(DOM), location(地址对象), history(历史对象)

    # 接收id，获取对象
    gid = request.GET.get('gid')

    # 判断是否为下架状态
    res = Goods.objects.filter(id=gid).filter(status='3').exists()#.count()
    print(gid,res)

    if not res:
        return JsonResponse({'msg':'该商品正在销售，不可删除','code':1})

    # 执行删除
    ob = Goods.objects.get(id=gid)
    ob.delete()

    return JsonResponse({'msg':'删除成功','code':0})

# 商品状态修改
@permission_required('myadmin.edit_Goods',raise_exception=True)
def good_status(request):
    # 通过uid获取 会员对象
    ob = Goods.objects.get(id=request.GET.get('gid'))
    # print(request.GET.get('gid'))
    # print(request.GET.get('status'))
    ob.status = request.GET.get('status')
    ob.save()
    return JsonResponse({'msg':'状态更新成功','code':0})

# 商品信息修改
@permission_required('myadmin.edit_Goods',raise_exception=True)
def good_edit(request):
    # 接受会员用户id
    gid = request.GET.get('gid')
    # 获取会员用户对象
    gob = Goods.objects.get(id=gid)

    # 判读当前的请求方式
    if request.method == 'POST':
        # 执行更新操作

        # 判断头像是否更新
        myfile = request.FILES.get('pic',None)
        if myfile:
            # 有新头像上传，则先删除原头像
            os.remove(BASE_DIR+gob.pic_url)
            # 更新头像
            uob.pic_url = uploads_pic(myfile)

        # 更新其他数据 --- 存对象Cates.objects.get(id=request.POST.get('cateid'))
        gob.cateid = Cates.objects.get(id=request.POST.get('cateid'))
        gob.goodsname = request.POST.get('goodsname')
        gob.title = request.POST.get('title')
        gob.price = request.POST.get('price')
        gob.goodsnum = request.POST.get('goodsnum')
        gob.goodsinfo = request.POST.get('goodsinfo')
        # print(gob.cateid,request.POST.get('cateid'))
        gob.save()

        return HttpResponse('<script>alert("更新成功");location.href="/myadmin/good/index/";</script>')

    elif request.method == 'GET':
        
        # 下拉框
        data = Cates.objects.all()
        catelist = get_cates_all(data)
        # 分配
        # catelist 为里面的数据  
        context = {'ginfo': gob,'catelist': catelist}
        return render(request,'myadmin/goods/edit.html/',context)

web/myadmin/views/OrderViews.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse

def myhome_pay_result(request):
    pass



# from web import settings
# from utils.pay import AliPay
# # AliPay 对象实例化
# def Get_AliPay_Object():
#     alipay = AliPay(
#         appid=settings.ALIPAY_APPID,  # APPID （沙箱应用）
#         app_notify_url=settings.ALIPAY_NOTIFY_URL,  # 回调通知地址
#         return_url=settings.ALIPAY_RETURN_URL,  # 支付完成后的跳转地址
#         app_private_key_path=settings.APP_PRIVATE_KEY_PATH,  # 应用私钥
#         alipay_public_key_path=settings.ALIPAY_PUBLIC_KEY_PATH,  # 支付宝公钥
#         debug=True,  # 默认False, -- 沙箱环境
#     )
#     return alipay

web/templates/myadmin/cates/add.html
{% extends 'myadmin/index.html' %}

{% block title %}
<title>后台商品分类添加</title>
{% endblock %}


{% block con %}
<div class="row-content am-cf">
    <div class="row">
        <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
            <div class="widget am-cf">
                <div class="widget-head am-cf">
                    <div class="widget-title am-fl">
                        商品分类添加
                    </div>
                    <div class="widget-function am-fr">
                        <a href="javascript:;" class="am-icon-cog">
                        </a>
                    </div>
                </div>
                <div class="widget-body am-fr">
                    <form action="{% url 'myadmin_cate_add' %}" method="POST" enctype="multipart/form-data" class="am-form tpl-form-line-form">
                        {% csrf_token %}

                        <div class="am-form-group">
                            <label for="user-name" class="am-u-sm-3 am-form-label">
                                分类名称
                            </label>
                            <div class="am-u-sm-9">
                                <input type="text" name="name" class="tpl-form-input" 
                                 placeholder="请输入类别">
                            </div>
                        </div>

                        <div class="am-form-group">
                            <label for="user-name" class="am-u-sm-3 am-form-label">
                                分类等级
                            </label>
                            <select name="pid" data-am-selected="{btnSize: 'sm'}" style="display: none;">
                                <option value="0">顶级</option> 
                                <!-- <option value="1">服装</option>  -->

                                {% for i in catelist %}
                                    <option value="{{i.id}}">{{i.tab}}{{i.name}}</option>
                                {% endfor %}
                            </select>  
                        </div>
                       
                        <div class="am-form-group">
                            <div class="am-u-sm-9 am-u-sm-push-3">
                                <button class="am-btn am-btn-primary tpl-btn-bg-color-success ">
                                    提交
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

web/templates/myadmin/cates/index.html
{% extends 'myadmin/index.html' %}

{% block title %}
<title>后台商品分类列表</title>
{% endblock %}


{% block con %}
<div class="row-content am-cf">
   <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
        <div class="widget am-cf">
            <div class="widget-head am-cf">
                <div class="widget-title  am-cf">商品分类列表</div>


            </div>
            <div class="widget-body  am-fr">

                <div class="am-u-sm-12 am-u-md-6 am-u-lg-6">
                    <div class="am-form-group">
                        <div class="am-btn-toolbar">
                            <div class="am-btn-group am-btn-group-xs">
                                <a href="{% url 'myadmin_cate_add' %}" type="button" class="am-btn am-btn-default am-btn-warning"><span class="am-icon-plus"></span> 新增</a>
                            </div>
                        </div>
                    </div>
                </div>

                <form>
                    <div class="am-u-sm-12 am-u-md-6 am-u-lg-3">
                        <div class="am-form-group tpl-table-list-select">
                            <select name="types" data-am-selected="{btnSize: 'sm'}" style="display: none;">
                              <option value="all" {% if request.GET.types == 'all' %}selected{% endif %}>所有</option>
                              <option value="id" {% if request.GET.types == 'id' %}selected{% endif %}>ID</option>
                              <option value="name" {% if request.GET.types == 'name' %}selected{% endif %}>商品类别</option>
                            </select>
                        </div>
                    </div>

                <div class="am-u-sm-12 am-u-md-12 am-u-lg-3">
                    <div class="am-input-group am-input-group-sm tpl-form-border-form cl-p">
                        <input type="text" value="{{request.GET.keywords}}" name="keywords" class="am-form-field ">
                        <span class="am-input-group-btn">
                            <button class="am-btn  am-btn-default am-btn-success tpl-table-list-field am-icon-search"></button>
                          </span>
                    </div>
                </div>
                </form>

                <div class="am-u-sm-12">
                    <table width="100%" class="am-table am-table-compact am-table-striped tpl-table-black ">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>商品类别</th>
                                <th>所属父级</th>
                                <th>商品数量</th>
                                <th>路径</th>
                                <th>操作</th>
                            </tr>
                        </thead>

                        <tbody>

                        {% for i in catelist %}
                            <tr class="gradeX">
                                
                                <td class="am-text-middle">{{i.id}}</td>
                                <td class="cate_name am-text-middle">
                                    <a href="javascript:void(0);">
                                        {{i.tab}}
                                        <span cid="{{i.id}}">{{i.name}}</span>
                                    </a>
                                </td>
                                <td class="am-text-middle">{{i.pid}} : <span>{{i.pname}}</span></td>
                                <td class="am-text-middle">{{i.goods_set.count |default:'空'}}</td>
                                <td class="am-text-middle">{{i.path}}</td>

                                <td class="am-text-middle">
                                    <div class="tpl-table-black-operation">
                                        <a href="javascript:void(0);" cid="{{i.id}}" class="removeCate tpl-table-black-operation-del">
                                            <i class="am-icon-trash"></i> 删除
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}    

                        </tbody>
                    </table>
                </div>
                <div class="am-u-lg-12 am-cf">

                    <div class="am-fr">
                        <ul class="am-pagination tpl-pagination">

                            {% load pagetag %}
                            <!-- userlist.paginator.num_pages 为总页数 -->
                            {% showPage userlist.paginator.num_pages request 6 %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    // 删除
    $('.removeCate').click(function(){
        // 获取商品分类的idname
        var cid = $(this).attr('cid')
        // alert(cid)
        // 存 删除的<a> 节点
        var a = $(this)

        $.get('{% url 'myadmin_cate_del' %}',
            {'cid':cid},
            function(data){
                // 判断当前的返回值
                if(data['code']==0){
                    // 删除整跳数据
                    // $(this).parents('tr').remove() // ajax中，this为XML Httprequest
                    a.parents('tr').remove()
                }
                alert(data['msg']);
            },'json')
    })

    // 编辑 -- name
    $('.cate_name').dblclick(function(){
        // 第一步
        // 获取name
        var catename = $(this).find('span').text()
        // alert(catename)
        // 添加标签
        var int = $('<input type="text" value="'+catename+'" style="width:100px">')
        // 标签替换
        $(this).find('span').html(int)
        // 让input的值 处于双击全选状态
        int.select()

        var span = $(this).find('span')
        // 获取id
        var cid = span.attr('cid')
        // 第二步 -- 失去焦点
        int.blur(function(){
            var newname=$(this).val()

            // 转回 span标签
            span.html(catename)

            // 那么是否被修改
            if(newname!=catename){
                $.get('{% url 'myadmin_cate_edit' %}',
                    {'cid':cid, 'newname':newname},
                    function(data){
                        if(data['code']==0){
                            span.html(newname)
                            // alert(data['msg'])
                        }
                    },'json')
            }
            
        })


    })
</script>
{% endblock %}